server:
  port: 8888
spring:
  redis:
  #单机版
#    host: 127.0.0.1
#    port: 6379

    cluster:
      nodes:
      - 127.0.0.1:6379
      - 127.0.0.1:6380
      - 127.0.0.1:6381

    sentinel:
      master: mymaster
      nodes:
      - 127.0.0.1:26379
    jedis:
      pool:
        max-active: 9  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 9    #连接池中的最大空闲连接
        min-idle: 0    #连接池中的最小空闲连接
    database: 0        #Redis数据库索引(默认为0)
    timeout: 60000     #连接超时时间（毫秒）
